github:
  prebuilds:
    main: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: true
    addLabel: prebuilt-in-gitpod
image: devimages/gitpod:latest
vscode:
  extensions:
    - denoland.vscode-deno
    - vscode.simple-browser
tasks:
  - init: mv /home/gitpod/monorepo/node_modules /workspace/monorepo/ && yarn
    command: echo 'start script'