github:
  prebuilds:
    main: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: true
    addLabel: prebuilt-in-gitpod
image: devimages/focal-devcontainer:13.0.14
vscode:
  extensions:
    - denoland.vscode-deno
