github:
  prebuilds:
    main: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: true
    addLabel: prebuilt-in-gitpod
image: devimages/hirsute-devcontainer:8.4.13
vscode:
  extensions:
    - denoland.vscode-deno
