github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: true
    addLabel: prebuilt-in-gitpod
vscode:
  extensions:
    - denoland.vscode-deno@2.3.3:aFOFUSjDJT7KDqulGrZ5zA==