github:
  prebuilds:
    main: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true
    addBadge: true
    addLabel: prebuilt-in-gitpod
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - denoland.vscode-deno
