nodeLinker: node-modules

enableScripts: false
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path:    .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
nmMode: "hardlinks-local"
enableImmutableCache: false
pnpEnableEsmLoader: true
supportedArchitectures:
  os:
   - darwin
   - linux
  cpu:
    - x86
    - arm64
    - amd64
