enableImmutableCache: false

enableScripts: true

globalFolder: .yarn/global

nmHoistingLimits: none

nmMode: hardlinks-global

nodeLinker: pnp

pnpMode: strict

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.0.0-rc.14.cjs


pnpIgnorePatterns:
  - sites/spike.land/**