
enableScripts: true

globalFolder: .yarn/global

nmHoistingLimits: none

nmMode: hardlinks-global

nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

pnpEnableEsmLoader: true

pnpIgnorePatterns:
  - sites/spike.land/**


yarnPath: .yarn/releases/yarn-3.2.2.cjs
