enableScripts: true

nmHoistingLimits: none
cacheFolder: .yarn/cache
globalFolder: .yarn/global

nodeLinker: pnp
pnpMode: strict

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpEnableEsmLoader: true

pnpFallbackMode: none
pnpEnableInlining: true

yarnPath: .yarn/releases/yarn-4.0.0-rc.24.cjs
