cacheFolder: .yarn/cache

enableScripts: true

globalFolder: .yarn/global

nmHoistingLimits: none

nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpEnableEsmLoader: true

pnpEnableInlining: true

pnpFallbackMode: none

pnpMode: strict

yarnPath: .yarn/releases/yarn-4.0.0-rc.24.cjs
