compressionLevel: mixed

enableGlobalCache: true

enableTelemetry: false

globalFolder: ./.yarn/global

nmMode: hardlinks-global

nodeLinker: pnp

pnpFallbackMode: all

yarnPath: .yarn/releases/yarn-4.4.0.cjs

packageExtensions:
  "@types/react@*":
    peerDependencies:
      react: "*"
  react@*:
    peerDependencies:
      "@types/react": "*"

pnpMode: loose
