compressionLevel: mixed

enableGlobalCache: true

enableTelemetry: false

globalFolder: ./.yarn/global

nmMode: hardlinks-global

nodeLinker: node-modules

pnpFallbackMode: all

pnpMode: strict

yarnPath: .yarn/releases/yarn-4.3.1.cjs
