enableGlobalCache: true

checksumBehavior: reset
nodeLinker: pnp
enableInlineBuilds: true
pnpEnableEsmLoader: true
pnpEnableInlining: true


pnpFallbackMode: all

pnpMode: strict

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.5.1.cjs
