services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${UID}
        USER_GID: ${GID}
    tmpfs:
      - /home/node/tmpfs:size=8gb,rw,uid=${UID},gid=${GID}
    shm_size: 8gb
    privileged: true
    environment:
      - USER=node
      - HOME=/home/node
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/home/node/workspace:rw
      - ${HOME}/.config:/home/node/.config
      - ${HOME}/.cache:/home/node/.cache
      - ${HOME}/.oh-my-zsh:/home/node/.oh-my-zsh
    ports:
      - "3333:3333"
