version: "3.9"
services:
  devcontainer: 
    image: devimages/bookw
    build: 
      dockerfile: packages/bookworm-devcontainer  
      context: .
    tmpfs:
      - /home/$USER/tmpfs:exec
    shm_size: 4gb
    privileged: true
    volumes:
      # - $HOME:/home/$USER/host:delegated
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "6080:6080"
      - "5901:5901"