version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: "${UID:-1000}"
        USER_GID: "${GID:-1000}"
        USERNAME: "node"
        USER_HOME: "/home/node"
    tmpfs:
      - /home/node/tmpfs:size=8g,rw,exec
    shm_size: 8gb
    # privileged: true  <-- Removed privileged flag.  Consider alternatives for security.
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: zsh -c "yarn && cd packages/code && yarn dev"
    volumes:
      - .:/home/node/workspace:cached
      - node_modules:/home/node/workspace/node_modules
      - yarn_cache:/home/node/.yarn/cache
      - ${HOME:-/home/node}/.config:/home/node/.config:cached
      - ${HOME:-/home/node}/.vscode:/home/node/.vscode:cached
      - ${HOME:-/home/node}/.vscode-server:/home/node/.vscode-server:cached
      - ${HOME:-/home/node}/.cache:/home/node/.cache:cached
      - ${HOME:-/home/node}/.oh-my-zsh:/home/node/.oh-my-zsh:cached
    ports:
      - "3333:3333"
      - "6080:6080"
      - "9222:9222"
      - "8080:8080"
    ipc: host
    init: true
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3333"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 2G

volumes:
  node_modules:
  yarn_cache:
