services:
  devcontainer: 
    image: devimages/bookworm-devcontainer  
    build: 
      dockerfile: ./packages/bookworm-devcontainer/Dockerfile 
      context: .
    tmpfs:
      - /home/$USER/tmpfs:exec
    shm_size: 4gb
    privileged: true
    volumes:
      # - $HOME:/home/$USER/host:delegated
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "6080:6080"
      - "5901:5901"