services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${UID}
        USER_GID: ${GID}
        USER: ${USER}
        HOME: ${HOME}
    tmpfs:
      - ${HOME}/tmpfs:size=8g,rw,exec,uid=${UID},gid=${GID}
    shm_size: 8gb
    # privileged: true  <-- Removed privileged flag.  Consider alternatives for security.
    environment:
      - USER=${USER}
      - HOME=${HOME}
    command: yarn dev #Start the development server
    volumes:
      - .:${HOME}/workspace:rw
      - ${HOME}/.config:/${HOME}/.config
      - ${HOME}/.vscode:${HOME}/.vscode
      - ${HOME}/.vscode-server:${HOME}/.vscode-server
      
      
      - ${HOME}/.cache:${HOME}/.cache
      - ${HOME}/.oh-my-zsh:${HOME}/.oh-my-zsh
    ports:
      - "3333:3333"
      - "6080:6080" # Added port 6080
      - "9222:9222" # Added port for Chrome DevTools
      - "8080:8080" # Added a generic port for other tools
