services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${UID}
        USER_GID: ${GID}
        USER: ${USER}
        HOME: ${HOME}
    tmpfs:
      - ${HOME}/tmpfs:size=8g,rw,exec,uid=${UID},gid=${GID}
    shm_size: 8gb
    # privileged: true  <-- Removed privileged flag.  Consider alternatives for security.
    environment:
      - USER=${USER}
      - HOME=${HOME}
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: zsh -c "yarn && cd packages/code && yarn dev"
    volumes:
      - .:/home/node/workspace:cached
      - node_modules:/home/node/workspace/node_modules
      - yarn_cache:/home/node/.yarn/cache
      - ${HOME}/.config:/home/node/.config:cached
      - ${HOME}/.vscode:/home/node/.vscode:cached
      - ${HOME}/.vscode-server:/home/node/.vscode-server:cached
      - ${HOME}/.cache:/home/node/.cache:cached
      - ${HOME}/.oh-my-zsh:/home/node/.oh-my-zsh:cached
    ports:
      - "3333:3333"
      - "6080:6080"
      - "9222:9222"
      - "8080:8080"
    ipc: host
    init: true
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3333"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 2G

volumes:
  node_modules:
  yarn_cache:
