version: '3.4'
services:
  # ipfs:
  #   image: ipfs/go-ipfs:latest
  #   ports: 
  #     - 4001:4001
  #     - 5001:5001
  #     - 8080:8080
  #   volumes:
  #     - ipfs:/data/ipfs
  #     - .:/exportdevcontainer
  devcontainer: 
    build: 
      context: .
      target: devcontainer
    # build: 
    #   context: .
    #   dockerfile: ./monorepo/dockerhub/devimages/jammy-devcontainer/Dockerfile
    #   args:
    #     - platform linux/amd64
    ports: 
      - 5901:5901
      - 6080:6080
    # privileged: true
    shm_size: 4gb
    volumes:
      # - $HOME:/home/$USER/host:delegated
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
volumes: 
  ipfs:
  node:
