
name = "transform"
# Add your account ID here
account_id = "1f98921051196545ebe79a450d3c71ed"
compatibility_date = "2021-10-16"
main = "./src/index.mjs"

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = false