
name = "transform"
# Add your account ID here
account_id = "1f98921051196545ebe79a450d3c71ed"
usage_model = "unbound"
compatibility_date = "2021-10-16"
main = "../code/dist/cf-esbuild.mjs"

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = false