name = "qwik-app"
type = "javascript"

account_id = "1f98921051196545ebe79a450d3c71ed"
workers_dev = true
route = "https://spike.land/*"
zone_id = "07e8952f4aa2d9e95f04a2b32a9cf084"
compatibility_date = "2021-12-13"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[site]
bucket = "public" # directory with your static assets
entry-point = "workers-site" # JS folder serving your assets
