name = "esbuild-worker"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
kv_namespaces = [
  { binding = "COUNTER_NAMESPACE", id = "", preview_id = "" },
]

[build]
command = "npm run build"
[build.upload]

[miniflare]
live_reload = true

[site]
bucket = "./public"
# Below options are optional
include = ["static"]
exclude = ["ignore_dir"]

[env.dev]

kv_namespaces = [{ binding = "__STATIC_CONTENT"}]

    