name = "spike-land"
workers_dev = true
# Add your account ID here
account_id = "1f98921051196545ebe79a450d3c71ed"
route = "https://spike.land/*"
compatibility_date = "2021-10-16"
usage_model = "bundled"

[durable_objects]
bindings = [
    { name = "CODE", class_name = "Code" },
    { name = "LIMITERS", class_name = "CodeRateLimiter" }
]