name = "spike-land"
# Add your account ID here
account_id = "1f98921051196545ebe79a450d3c71ed"
route = "https://spike.land/*"  
compatibility_date = "2021-10-16"
usage_model = "bundled"
main = "dist/worker.mjs"

[durable_objects]
bindings = [
    { name = "CODE", class_name = "Code" },
    { name = "LIMITERS", class_name = "CodeRateLimiter" }
]

[[migrations]]
tag = "v2" # Should be unique for each entry
new_classes = ["Code", "CodeRateLimiter"] # Array of new classes

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Users"] # Array of new classes

[site]
bucket = "./public" # Add the directory with your static assets


[env.dev]
name = "spike-land-dev"
route = "https://dev.spike.land/*"

migrations = [
    {tag = "v3", new_classes= ["Users", "Code", "CodeRateLimiter"]}
]

durable_objects.bindings = [
    { name = "CODE", class_name = "Code" },
    { name = "LIMITERS", class_name = "CodeRateLimiter" }
]

site.bucket = "./public"

