name = "spike-land"
type = "javascript"
workers_dev = true
# Add your account ID here
account_id = "1f98921051196545ebe79a450d3c71ed"
zone_id = "07e8952f4aa2d9e95f04a2b32a9cf084"
route = "https://spike.land/*"
compatibility_date = "2021-10-16"

[durable_objects]
bindings = [
    { name = "CODE", class_name = "Code" },
    { name = "LIMITERS", class_name = "CodeRateLimiter" }
]