
name = "spike-land"
# Add your account ID here
account_id = "1f98921051196545ebe79a450d3c71ed"
usage_model = "unbound"
compatibility_date = "2021-10-16"
main = "../code/dist/cf-workers.mjs"


[durable_objects]
bindings = [
    { name = "CODE", class_name = "Code" },
    { name = "LIMITERS", class_name = "CodeRateLimiter" }
]

# [[r2_buckets]]
# binding = "R2_BUCKET" 
# bucket_name = "ze3w"

[[migrations]]
tag = "v2" # Should be unique for each entry
new_classes = ["Code", "CodeRateLimiter"] # Array of new classes

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Users"] # Array of new classes

[site]
bucket = "../code/dist" # Add the directory with your static assets
 
[env.testing]
name = "testing-spike-land"
usage_model = "unbound"


[[env.testing.migrations]]
tag = "v4" 
new_classes= ["Users", "Code", "CodeRateLimiter"]




[env.testing.durable_objects]
bindings = [
    { name = "CODE", class_name = "Code" },
    { name = "LIMITERS", class_name = "CodeRateLimiter" }
]


# [[env.testing.r2_buckets]]
# binding = "R2_BUCKET" 
# bucket_name = "ze3w"