name = "spike-land"
# Add your account ID here
account_id = "1f98921051196545ebe79a450d3c71ed"
usage_model = "unbound"
compatibility_date = "2021-10-16"
main = " dist/index.js"

[durable_objects]
bindings = [
    { name = "CODE", class_name = "Code" },
    { name = "LIMITERS", class_name = "CodeRateLimiter" }
]

[[migrations]]
tag = "v2" # Should be unique for each entry
new_classes = ["Code", "CodeRateLimiter"] # Array of new classes

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Users"] # Array of new classes





[site]
bucket = "../../packages/code/dist" # Add the directory with your static assets


[env.testing]
name = "testing-spike-land"


[[env.testing.migrations]]
tag = "v4" 
new_classes= ["Users", "Code", "CodeRateLimiter"]

[env.testing.durable_objects]
bindings = [
    { name = "CODE", class_name = "Code" },
    { name = "LIMITERS", class_name = "CodeRateLimiter" }
]

