version: "3.7"
services:
  devcontainer:
    build: 
      context: .
      args: 
        USER: $USER
    tmpfs: 
      - /home/$USER/tmpfs:exec
    privileged: true
    shm_size: 8gb
    volumes: 
      - /home:/home
      - yarn:/yarn
    ports:
      - "6080:6080"
      - "5901:5901"
volumes: 
  yarn: 