name = "chat-spike-land"
type = "javascript"
workers_dev = true
# Add your account ID here
account_id = "1f98921051196545ebe79a450d3c71ed"
zone_id = "07e8952f4aa2d9e95f04a2b32a9cf084"
route = "https://chat.spike.land/*"
compatibility_date = "2021-10-16"

[build.upload]
format = "modules"
dir = "src"
main = "./chat.mjs"
rules = [{type = "Data", globs = ["**/*.html"]}]

[durable_objects]
bindings = [
  { name = "rooms", class_name = "ChatRoom" },
  { name = "limiters", class_name = "RateLimiter" }
]
