name = "durable-objects-rollup-esm"
type = "javascript"
account_id = "1f98921051196545ebe79a450d3c71ed"
workers_dev = true
route = "https://counter.spike.land/*"
zone_id = "07e8952f4aa2d9e95f04a2b32a9cf084"
compatibility_flags = []
compatibility_date = "2021-10-01"
[build]
command = "yarn build"
[build.upload]
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"
[durable_objects]
bindings = [{name = "COUNTER", class_name = "Counter"}]

