version: "3.7"
services:
  ipfs: 
    image: ipfs/go-ipfs:latest
    # ports: 
    #   - 4000:4000
    #   - 4001:4001
    #   - 5001:5001
    #   - 8080:8080
    #   - 8081:8081
    volumes:
      - ipfs:/ipfs
      - ipns:/ipns

  devcontainer: 
    image: devimages/hirsute-devcontainer:latest
    # build:
    #   context: .
    #   args:
    #     USER: $USER
    tmpfs:
      - /home/$USER/tmpfs:exec
    privileged: true
    shm_size: 4gb
    network_mode: host
    volumes:
      # - $HOME:/home/$USER/host:delegated
      - /var/run/docker.sock:/var/run/docker.sock
      - ipfs:/ipfs
      - ipns:/ipns
      - yarn:/yarn
    ports:
      - "6080:6080"
      - "5901:5901"
volumes:
  yarn:
  ipfs:
  ipns:
   