name = "my-ts-project"
type = "webpack"
account_id = "1f98921051196545ebe79a450d3c71ed"
workers_dev = true
route = ""
zone_id = "ec8e903035c7b0fcd3e95f1e483ab68c"
webpack_config = "webpack.config.js"
kv_namespaces = [
  { binding = "SHATEST", id = "23ad5069f6c24f69a1ac62cfecd9fe19" }
]