name: Update DockerHub Images

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: "!contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        image-name: [cypress,  eoan-xfce-novnc, gitpod, focal-devcontainer,  groovy-devcontainer,  groovy-xfce-novnc,  hirsute-devcontainer, rolling-devcontainer]

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Package Version
        uses: Saionaro/extract-package-version@v1.1.1
        with:
          path: dockerhub/devimages/${{ matrix.image-name }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./dockerhub/devimages/${{ matrix.image-name }}/Dockerfile
          push: true
          tags: devimages/${{ matrix.image-name }}:latest, devimages/${{ matrix.image-name }}:${{ steps.extract_version.outputs.version }}          
          cache-from: type=registry,ref=devimages/${{ matrix.image-name }}:buildcache
          cache-to: type=registry,ref=devimages/${{ matrix.image-name }}:buildcache,mode=max
