name: Update API Dockerhub Images

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - uses: actions/checkout@master

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/docker_cache
            !~/cache/exclude
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./packages/groovy-devcontainer/Dockerfile
          push: true
          cache-from: |
            devimages/groovy-devcontainer:latest
            type=local,src=~/docker_cache
          tags: devimages/groovy-devcontainer:latest

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Dockerhub Release
        run: ./scripts/release-dockerhub.sh -s api
