name: Wrangler

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Wrangler
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          workingDirectory: 'monorepo/sites/spike.land'
          apiToken: ${{ secrets.CF_API_TOKEN }}