
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${UID}
        USER_GID: ${GID}
        USER: ${USER}
    tmpfs:
      - /home/${USER}:exec,size=8g,uid=${UID},gid=${GID}
    command: >
      /bin/sh -c "
      chown -R ${USER}:${USER} /home/${USER} &&
      su - ${USER} -c '/usr/bin/startWithBash'
      "
    environment:
      - USER=${USER}
    volumes:
      - ${HOME}/.config:/home/${USER}/.config:ro
      - ${HOME}/.cache:/home/${USER}/.cache:ro
      - ${HOME}/.oh-my-zsh:/home/${USER}/.oh-my-zsh:ro
    ports:
      - 6080:6080
      - 5901:5901