version: "3.4"
services:
  devcontainer:
    image: devimages/groovy-xfce-novnc:latest
    tmpfs:
      - /home/$USER/tmpfs:exec
    network_mode: host
    privileged: true
    shm_size: 4gb
    volumes:
      # - $HOME:/home/$USER/host:delegated
      - /var/run/docker.sock:/var/run/docker.sock
      - yarn:/yarn
    ports:
      - "6080:6080"
      - "5901:5901"
volumes:
  yarn:
